# Build settings
destination: _site
exclude: [
  Gemfile,
  Gemfile.lock,
  LICENSE,
  LICENSE_FOR_CONTENTS,
  LICENSE_FOR_SOFTWARE,
  README.md,
  package.json,
  package-lock.json,
  yarn.lock,
  node_modules,
  vendor,
  firebase.json,
  deploy.sh
  ]

# Site settings
title: 石橋秀仁
author: 石橋秀仁
thumbnail: /assets/thumbnail.jpg
email: hide@hideishi.com
description: "ソフトウェア開発者／情報アーキテクト(IA)"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hideishi.com" # the base hostname & protocol for your site
twitter_username: zerobase
github_username:  zerobase
google_analytics_tracking_id: UA-41591703-2

## Custom settings
show_facebook_comment: false

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-linkpreview
  - jekyll-figure
  - jekyll-extlinks
  - jekyll-tidy
extlinks:
  attributes: {target: _blank}
  # rel_exclude: ['host1.com', 'host2.net']

# Blog
permalink: date # previously: /blog/:categories/:title/

# Default variables

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "石橋秀仁 (Hideto Ishibashi)"
  -
    scope:
      path: "_posts/blog"
    values:
      categories: "blog"
  -
    scope:
      path: "_posts/activity"
    values:
      categories: "activity"
  -
    scope:
      path: "_posts/podcast"
    values:
      categories: "podcast"
