# Build settings
destination: public
exclude: [
  CNAME,
  Gemfile,
  Gemfile.lock,
  LICENSE,
  LICENSE_FOR_CONTENTS,
  LICENSE_FOR_SOFTWARE,
  README.md,
  package.json,
  package-lock.json,
  yarn.lock,
  node_modules,
  vendor,
  firebase.json
  ]

# Site settings
title: 石橋秀仁 (Hide Ishi)
author: 石橋秀仁 (Hide Ishi)
thumbnail: /assets/thumbnail.png
email: hide@hideishi.com
description: "an information architect / インフォメーション・アーキテクト"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hideishi.com" # the base hostname & protocol for your site
twitter_username: zerobase
github_username:  zerobase
main_feed: https://feeds.feedburner.com/HidetoIshibashi
podcast_feed: https://feeds.feedburner.com/InformationArchitectsPodcast
podcast_itunes_url: https://itunes.apple.com/jp/podcast/ia-podcast/id963102127?l=en&mt=2

## Custom settings
show_facebook_comment: false

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-linkpreview
  - jekyll-figure
  - jekyll-extlinks
  - jekyll-tidy
extlinks:
  attributes: {target: _blank}
  # rel_exclude: ['host1.com', 'host2.net']

# Blog
permalink: date # previously: /blog/:categories/:title/

# Default variables

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "石橋秀仁 (Hide Ishi)"
  -
    scope:
      path: "_posts/blog"
    values:
      categories: "blog"
  -
    scope:
      path: "_posts/activity"
    values:
      categories: "activity"
  -
    scope:
      path: "_posts/podcast"
    values:
      categories: "podcast"

# Twitter
twitter_user: zerobase
twitter_tweet_button: true

# Facebook
facebook_app_id: 422391257870402
facebook_locale: ja_JP

# Google Analytics
google_analytics_tracking_id: UA-41591703-2
