# Build settings
exclude: [CNAME, Gemfile, Gemfile.lock, LICENSE, LICENSE_FOR_CONTENTS, LICENSE_FOR_SOFTWARE, README.md]
destination: public

# Site settings
title: Hideto Ishibashi
#lead: "an information architect"
author: Hideto Ishibashi
author_link: https://plus.google.com/+IshibashiHideto/
thumbnail: http://ja.ishibashihideto.net/images/thumbnail.png
email: hidetoi@gmail.com
description: "an information architect / インフォメーション・アーキテクト"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ja.ishibashihideto.net" # the base hostname & protocol for your site
twitter_username: zerobase
github_username:  zerobase
main_feed: http://feeds.feedburner.com/HidetoIshibashi
podcast_feed: http://feeds.feedburner.com/InformationArchitectsPodcast
podcast_itunes_url: https://itunes.apple.com/jp/podcast/ia-podcast/id963102127?l=en&mt=2

## Custom settings
show_header_nickname: false
show_lang_switcher: false
show_facebook_comment: false

## Category settings

category_labels:
  blog: 石橋秀仁のブログ
  activity: 石橋秀仁の活動報告
  podcast: 石橋秀仁のポッドキャスト
  about: 石橋秀仁について

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-timeago
jekyll_timeago:
  depth: 1 # Level of detail

# Blog
permalink: date # previously: /blog/:categories/:title/

# Default variables

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "石橋秀仁"

# Twitter
twitter_user: zerobase
twitter_tweet_button: true

# Facebook
facebook_app_id: 422391257870402
facebook_locale: ja_JP

# Google Analytics
google_analytics_tracking_id: UA-41591703-2
