version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          BUNDLER_VERSION: 2.1.4
          BUNDLE_PATH: vendor/bundle
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
    steps:
      - checkout
      - run: gem install bundler:2.1.4
      - run: bundle -v
      - restore_cache:
          keys:
          - gem-cache-v1-{{ checksum "Gemfile.lock" }}
          - gem-cache-v1-
      - run: bundle check || bundle install
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
          - node-cache-v1-{{ checksum "yarn.lock" }}
          - node-cache-v1-
      - run: yarn install
      - save_cache:
          key: node-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: bundle exec jekyll build --verbose --future
      - run: yarn run firebase use $FIREBASE_PROJECT
      - run: yarn run firebase deploy --token=$FIREBASE_TOKEN --non-interactive
